/**
 * External Paste Detector for Browser AI
 *
 * Implements J6-E05: Detect code pasted from browser AI tools
 *
 * Analyzes clipboard paste events to detect AI-generated code from
 * browser-based AI tools (ChatGPT, Claude, etc.) through pattern matching.
 *
 * @module ai/ExternalPasteDetector
 */

/**
 * Paste analysis result
 */
export interface PasteAnalysis {
	isLikelyAI: boolean;
	confidence: number;
	indicators: string[];
	source: string;
}

/**
 * External paste detector for browser AI
 *
 * Detects AI-generated code pasted from browser tools through:
 * - Explicit AI comment markers
 * - Perfect formatting patterns
 * - Complete function/class definitions
 * - Comprehensive error handling
 */
export class ExternalPasteDetector {
	// Common AI code patterns
	private static readonly AI_INDICATORS = {
		// Comment patterns often added by AI
		COMMENT_PATTERNS: [
			/\/\/ Generated by/i,
			/\/\/ AI-generated/i,
			/\/\* AI Assistant/i,
			/# Generated with/i,
			/"""AI-generated/i,
		],
		// Structural patterns common in AI output
		STRUCTURE_PATTERNS: [
			// Perfect formatting with consistent spacing
			/^(\s{2}|\s{4}|\t)+/gm,
			// Type annotations on every parameter (over-annotation)
			/\([\w]+:\s*\w+(?:,\s*[\w]+:\s*\w+){3,}\)/,
		],
		// Naming conventions that suggest AI
		NAMING_PATTERNS: [
			// Generic names like "data", "result", "item"
			/\b(data|result|item|element|value|temp|obj)\b/gi,
		],
	};

	// Minimum paste size to analyze (very small pastes are likely not AI)
	private static readonly MIN_ANALYZE_LENGTH = 50;

	// Large paste threshold (large pastes more likely from AI)
	private static readonly LARGE_PASTE_THRESHOLD = 500;

	/**
	 * Analyze pasted content for AI indicators
	 */
	analyzePaste(content: string, timeSinceLastKeystroke: number): PasteAnalysis {
		if (content.length < ExternalPasteDetector.MIN_ANALYZE_LENGTH) {
			return {
				isLikelyAI: false,
				confidence: 0,
				indicators: [],
				source: "clipboard",
			};
		}

		const indicators: string[] = [];
		let confidence = 0;

		// Check for explicit AI markers
		for (const pattern of ExternalPasteDetector.AI_INDICATORS.COMMENT_PATTERNS) {
			if (pattern.test(content)) {
				indicators.push("ai_comment_marker");
				confidence += 0.4;
			}
		}

		// Large paste after long pause suggests copy from external source
		if (content.length > ExternalPasteDetector.LARGE_PASTE_THRESHOLD) {
			indicators.push("large_paste");
			confidence += 0.2;

			if (timeSinceLastKeystroke > 5000) {
				// >5 seconds
				indicators.push("long_pause_before_paste");
				confidence += 0.15;
			}
		}

		// Check for overly perfect formatting
		const lines = content.split("\n");
		if (lines.length > 5) {
			const indentConsistency = this.checkIndentConsistency(lines);
			if (indentConsistency > 0.95) {
				indicators.push("perfect_formatting");
				confidence += 0.1;
			}
		}

		// Check for complete function/class definitions
		if (this.hasCompleteDefinition(content)) {
			indicators.push("complete_definition");
			confidence += 0.15;
		}

		// Check for comprehensive error handling (AI tends to add this)
		if (this.hasComprehensiveErrorHandling(content)) {
			indicators.push("comprehensive_error_handling");
			confidence += 0.1;
		}

		// Cap confidence at 1.0
		confidence = Math.min(confidence, 1.0);

		return {
			isLikelyAI: confidence >= 0.4,
			confidence,
			indicators,
			source: "clipboard",
		};
	}

	/**
	 * Check consistency of indentation across lines
	 */
	private checkIndentConsistency(lines: string[]): number {
		const indents = lines
			.filter((l) => l.trim().length > 0)
			.map((l) => {
				const match = l.match(/^(\s*)/);
				return match ? match[1].length : 0;
			});

		if (indents.length < 2) return 0;

		// Check if indents follow a consistent pattern (multiples of 2 or 4)
		const mod2Consistent = indents.every((i) => i % 2 === 0);
		const mod4Consistent = indents.every((i) => i % 4 === 0);

		return mod4Consistent ? 1.0 : mod2Consistent ? 0.8 : 0.5;
	}

	/**
	 * Check if content has complete function/class definition
	 */
	private hasCompleteDefinition(content: string): boolean {
		// Function with JSDoc
		if (/\/\*\*[\s\S]*?\*\/\s*(export\s+)?(async\s+)?function/.test(content)) {
			return true;
		}

		// Class definition
		if (/class\s+\w+\s*(extends|implements|{)/.test(content)) {
			return true;
		}

		// React component
		if (/export\s+(default\s+)?function\s+\w+\s*\([^)]*\)\s*{[\s\S]*return\s*\(/.test(content)) {
			return true;
		}

		return false;
	}

	/**
	 * Check for comprehensive error handling patterns
	 */
	private hasComprehensiveErrorHandling(content: string): boolean {
		const tryCount = (content.match(/try\s*{/g) || []).length;
		const catchCount = (content.match(/catch\s*\(/g) || []).length;
		const throwCount = (content.match(/throw\s+new\s+\w*Error/g) || []).length;

		// AI often adds try-catch around everything
		return tryCount >= 2 || (tryCount >= 1 && throwCount >= 2);
	}

	/**
	 * Track paste events and correlate with external activity
	 */
	trackPasteCorrelation(
		pasteTimestamp: number,
		browserActivityTimestamp?: number,
	): {
		correlationScore: number;
		timeGap: number | null;
	} {
		if (!browserActivityTimestamp) {
			return { correlationScore: 0, timeGap: null };
		}

		const timeGap = pasteTimestamp - browserActivityTimestamp;

		// If paste happened within 30 seconds of browser activity, likely correlated
		if (timeGap >= 0 && timeGap < 30000) {
			return {
				correlationScore: Math.max(0, 1 - timeGap / 30000),
				timeGap,
			};
		}

		return { correlationScore: 0, timeGap };
	}
}
