/**
 * J6 AI Detection Journey Tests
 *
 * Spec Reference: unified_ux_spec_UPDATED.md §3.7
 *
 * Edge Cases Covered:
 *   - J6-E05: Code pasted from browser AI (Gap → Implementing)
 *   - J6-E07: AI in terminal (Gap → Implementing)
 *
 * TDD Approach: RED → GREEN → REFACTOR
 */

import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { ExternalPasteDetector, type PasteAnalysis } from "../../../src/ai/ExternalPasteDetector";
import { TerminalAIDetector, type TerminalActivity } from "../../../src/ai/TerminalAIDetector";

// Mock vscode
vi.mock("vscode", () => ({
	window: {
		showInformationMessage: vi.fn(),
		onDidChangeActiveTerminal: vi.fn(() => ({ dispose: vi.fn() })),
		terminals: [],
	},
	workspace: {
		onDidChangeTextDocument: vi.fn(() => ({ dispose: vi.fn() })),
	},
	env: {
		clipboard: {
			readText: vi.fn(),
		},
	},
	EventEmitter: vi.fn().mockImplementation(() => ({
		event: vi.fn(),
		fire: vi.fn(),
		dispose: vi.fn(),
	})),
}));

// Mock logger
vi.mock("../../../src/utils/logger", () => ({
	logger: {
		info: vi.fn(),
		debug: vi.fn(),
		warn: vi.fn(),
		error: vi.fn(),
	},
}));

describe("J6 AI Detection Journey", () => {
	beforeEach(() => {
		vi.clearAllMocks();
	});

	afterEach(() => {
		vi.restoreAllMocks();
	});

	describe("J6-E05: Code pasted from browser AI", () => {
		let detector: ExternalPasteDetector;

		beforeEach(() => {
			detector = new ExternalPasteDetector();
		});

		describe("Paste Analysis", () => {
			it("should not flag small pastes", () => {
				const result = detector.analyzePaste("const x = 1;", 1000);

				expect(result.isLikelyAI).toBe(false);
				expect(result.confidence).toBe(0);
			});

			it("should detect AI comment markers", () => {
				const content = `// Generated by ChatGPT
function calculateSum(a, b) {
  return a + b;
}`;
				const result = detector.analyzePaste(content, 1000);

				expect(result.isLikelyAI).toBe(true);
				expect(result.indicators).toContain("ai_comment_marker");
				expect(result.confidence).toBeGreaterThanOrEqual(0.4);
			});

			it("should flag large pastes after long pause", () => {
				const content = `
function processData(input) {
  // Validate input
  if (!input) {
    throw new Error('Input is required');
  }

  // Process the data
  const result = input.map(item => ({
    id: item.id,
    name: item.name,
    value: item.value * 2
  }));

  // Return processed result
  return result;
}`.repeat(3); // Make it large enough

				const result = detector.analyzePaste(content, 10000); // 10 second pause

				expect(result.indicators).toContain("large_paste");
				expect(result.indicators).toContain("long_pause_before_paste");
			});

			it("should detect comprehensive error handling pattern", () => {
				const content = `
async function fetchData(url) {
  try {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(\`HTTP error! status: \${response.status}\`);
    }
    return await response.json();
  } catch (error) {
    if (error instanceof TypeError) {
      throw new Error('Network error occurred');
    }
    throw error;
  }
}

async function processRequest(data) {
  try {
    const validated = validateData(data);
    const result = await processData(validated);
    return { success: true, data: result };
  } catch (error) {
    console.error('Processing failed:', error);
    throw new Error('Failed to process request');
  }
}`;
				const result = detector.analyzePaste(content, 1000);

				expect(result.indicators).toContain("comprehensive_error_handling");
			});

			it("should detect complete function definitions", () => {
				const content = `
/**
 * Calculates the factorial of a number
 * @param n - The number to calculate factorial for
 * @returns The factorial result
 */
export function factorial(n: number): number {
  if (n < 0) {
    throw new Error('Negative numbers not allowed');
  }
  if (n <= 1) return 1;
  return n * factorial(n - 1);
}`;
				const result = detector.analyzePaste(content, 1000);

				expect(result.indicators).toContain("complete_definition");
			});
		});

		describe("Paste Correlation", () => {
			it("should correlate paste with recent browser activity", () => {
				const now = Date.now();
				const browserActivity = now - 5000; // 5 seconds ago

				const result = detector.trackPasteCorrelation(now, browserActivity);

				expect(result.correlationScore).toBeGreaterThan(0.8);
				expect(result.timeGap).toBe(5000);
			});

			it("should not correlate old browser activity", () => {
				const now = Date.now();
				const browserActivity = now - 60000; // 60 seconds ago

				const result = detector.trackPasteCorrelation(now, browserActivity);

				expect(result.correlationScore).toBe(0);
			});

			it("should handle no browser activity", () => {
				const result = detector.trackPasteCorrelation(Date.now(), undefined);

				expect(result.correlationScore).toBe(0);
				expect(result.timeGap).toBeNull();
			});
		});
	});

	describe("J6-E07: AI in terminal (not editor)", () => {
		let detector: TerminalAIDetector;

		beforeEach(() => {
			detector = new TerminalAIDetector();
		});

		describe("Command Analysis", () => {
			it("should detect GPT CLI usage", () => {
				const result = detector.analyzeCommand("gpt 'write a function'");

				expect(result.hasAITool).toBe(true);
				expect(result.toolName).toBe("GPT CLI");
				expect(result.confidence).toBeGreaterThanOrEqual(0.9);
			});

			it("should detect Claude CLI usage", () => {
				const result = detector.analyzeCommand("claude chat 'help me code'");

				expect(result.hasAITool).toBe(true);
				expect(result.toolName).toBe("Claude CLI");
			});

			it("should detect GitHub Copilot CLI", () => {
				const result = detector.analyzeCommand("gh copilot suggest");

				expect(result.hasAITool).toBe(true);
				expect(result.toolName).toBe("GitHub Copilot CLI");
			});

			it("should detect Aider", () => {
				const result = detector.analyzeCommand("aider --model gpt-4 src/main.ts");

				expect(result.hasAITool).toBe(true);
				expect(result.toolName).toBe("Aider");
			});

			it("should detect Ollama", () => {
				const result = detector.analyzeCommand("ollama run llama2");

				expect(result.hasAITool).toBe(true);
				expect(result.toolName).toBe("Ollama");
			});

			it("should detect AI model flags", () => {
				const result = detector.analyzeCommand("my-script --model llama-7b");

				expect(result.hasAITool).toBe(true);
				expect(result.toolName).toBe("AI Model Flag");
			});

			it("should detect curl to AI APIs", () => {
				const result = detector.analyzeCommand(
					'curl https://api.openai.com/v1/chat/completions -d \'{"model":"gpt-4"}\''
				);

				expect(result.hasAITool).toBe(true);
			});

			it("should not flag regular commands", () => {
				const result = detector.analyzeCommand("npm install express");

				expect(result.hasAITool).toBe(false);
				expect(result.confidence).toBe(0);
			});
		});

		describe("Output Analysis", () => {
			it("should detect markdown code blocks in output", () => {
				const output = `
Here's the code:

\`\`\`typescript
function hello() {
  console.log('Hello!');
}
\`\`\`
`;
				const result = detector.analyzeOutput(output);

				expect(result.containsGeneratedCode).toBe(true);
				expect(result.codeBlocks).toBe(1);
			});

			it("should detect multiple code blocks", () => {
				const output = `
\`\`\`javascript
const a = 1;
\`\`\`

And also:

\`\`\`javascript
const b = 2;
\`\`\`
`;
				const result = detector.analyzeOutput(output);

				expect(result.containsGeneratedCode).toBe(true);
				expect(result.codeBlocks).toBe(2);
				expect(result.confidence).toBeGreaterThan(0.5);
			});

			it("should detect AI response patterns", () => {
				const output =
					"Here's the code you requested:\n\nfunction add(a, b) { return a + b; }";

				const result = detector.analyzeOutput(output);

				expect(result.containsGeneratedCode).toBe(true);
			});

			it("should not flag normal terminal output", () => {
				const output = `
> npm install
added 50 packages in 2s
`;
				const result = detector.analyzeOutput(output);

				expect(result.containsGeneratedCode).toBe(false);
			});
		});

		describe("Session Tracking", () => {
			it("should track AI commands in session", () => {
				const tracker = detector.createSessionTracker();

				tracker.recordCommand("npm install");
				tracker.recordCommand("claude chat 'help'");
				tracker.recordCommand("gpt 'write code'");
				tracker.recordCommand("ls -la");

				const summary = tracker.getActivitySummary();

				expect(summary.aiCommandCount).toBe(2);
				expect(summary.tools).toContain("Claude CLI");
				expect(summary.tools).toContain("GPT CLI");
			});

			it("should track AI output in session", () => {
				const tracker = detector.createSessionTracker();

				tracker.recordOutput("normal output");
				tracker.recordOutput("```js\nconst x = 1;\n```");
				tracker.recordOutput("Here's the solution:\n```python\nprint('hi')\n```");

				const summary = tracker.getActivitySummary();

				expect(summary.aiOutputCount).toBe(2);
			});

			it("should provide complete activity summary", () => {
				const tracker = detector.createSessionTracker();

				tracker.recordCommand("aider --model claude-3");
				tracker.recordOutput("```ts\nfunction test() {}\n```");

				const summary = tracker.getActivitySummary();

				expect(summary.aiCommandCount).toBe(1);
				expect(summary.aiOutputCount).toBe(1);
				expect(summary.tools).toContain("Aider");
			});
		});
	});
});
